@startuml
    class CounterUI {
        +update()
    }
    interface CounterI {
        +increment()
        +decrement()
        +reset()
        +getValue()
    }
    class Counter {
        +increment()
        +decrement()
        +reset()
        +getValue()
    }
    class CounterCtrl {
        +plus()
        +minus()
        +reset()
        ~setUI()
    }
    CounterUI -> CounterI: counter
    CounterCtrl -> CounterUI: ui
    Counter --|> CounterI: extends
    CounterCtrl -> CounterI: counter
    CounterUI ..> CounterCtrl :uses
    Counter <.. MainApp: creates
    CounterCtrl <.. MainApp: creates
    CounterUI <.. MainApp: creates
@enduml